PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sch: <http://schema.org/>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX void: <http://schema.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX : <http://www.data.gov.ma/data/fr/group/education/ontology.owl#>

#etab-bts-public-men-2013-2014.csv
#etab-cpge-public-men-2013-2014.csv

#NOMETABLISSEMENT,ADRESSE,VILLE,TEL,EMAIL,CYCLE,REGION,PROVINCE,COMMUNE


CONSTRUCT {
  ?URI a <http://schema.org/CollegeOrUniversity/>;
    sch:name ?NOMFR;
    sch:streetAddress ?addfr;
    sch:telephone ?TEL;
    sch:email ?EMAIL;
    sch:addressLocality ?PROVINCE;
    sch:addressRegion ?REGION;
    :isPublic "true"^^xsd:boolean;
} 

WHERE { 
	BIND (URI(CONCAT('http://www.data.gov.ma/Education#', REPLACE(?NOMETABLISSEMENT,"\\s","_"), ?PROVINCE)) AS ?URI)
	BIND (STRLANG(?NOMETABLISSEMENT, 'fr-FR') AS ?NOMFR)
	BIND (STRLANG(?ADRESSE, 'fr-FR') AS ?addfr)
}
